### PR TITLE
javascript is dumb you should use discord.py

### PR DESCRIPTION
**Pull request by Duued**
javascript is dumb you should use discord.py

### CODE REVIEW

**Comment by Duued** [comment]
i didnt do anything destructive i just put a line saying `javascript is dumb you should use discord.py`

**Comment by Duued** [comment]
please use discord.py thanks :)

**Comment by zanderp25** [comment]
1. The single comment is pointless
2. Yes I can see what you did
3. Some people prefer JavaScript over Python
4. You admitted yourself that you don’t know discord.js

**Comment by Duued** [comment]
1. ok and
2. nice job
3. ew
4. ok and?

**Comment by zanderp25** [comment]
There is no reason to make a pull request if it has no function.

**Comment by zanderp25** [comment]
Also I think Discord.js is more organized, but I haven’t gotten that much into it yet

**Comment by zanderp25** [comment]
Wait what

**Comment by TheDummi** [comment]
You don't think its more organised, it just is more organised.

**Comment by zanderp25** [comment]
Well, yeah, that’s what I meant

**Comment by TheDummi** [comment]
Good

**Pull request closed without merging**
